package com.example.caloriemeter

import android.content.ContentValues
import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper
import android.util.Log

class DatabaseHelper(context: Context) : SQLiteOpenHelper(context, DATABASE_NAME, null, DATABASE_VERSION) {

    override fun onCreate(db: SQLiteDatabase) {
        Log.d("DatabaseHelper", "Creating tables")
        db.execSQL("CREATE TABLE Product (id INTEGER PRIMARY KEY, name TEXT, name_en TEXT, calories_per_100g INTEGER)")
        db.execSQL("CREATE TABLE Consumption (id INTEGER PRIMARY KEY, meal_time TEXT, product_id INTEGER, grams INTEGER, FOREIGN KEY(product_id) REFERENCES Product(id))")
        populateInitialData(db)
    }

    override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) {
        Log.d("DatabaseHelper", "Upgrading database from version $oldVersion to $newVersion")
        db.execSQL("DROP TABLE IF EXISTS Consumption")
        db.execSQL("DROP TABLE IF EXISTS Product")
        onCreate(db)
    }

    private fun populateInitialData(db: SQLiteDatabase) {
        val products = listOf(
            Product("Яблоко", "Apple", 52),
            Product("Банан", "Banana", 96),
            Product("Апельсин", "Orange", 47),
            Product("Груша", "Pear", 57),
            Product("Виноград", "Grape", 69),
            Product("Клубника", "Strawberry", 32),
            Product("Черника", "Blueberry", 57),
            Product("Арбуз", "Watermelon", 30),
            Product("Дыня", "Melon", 34),
            Product("Ананас", "Pineapple", 50),
            Product("Манго", "Mango", 60),
            Product("Киви", "Kiwi", 61),
            Product("Гранат", "Pomegranate", 83),
            Product("Персик", "Peach", 39),
            Product("Абрикос", "Apricot", 48),
            Product("Вишня", "Cherry", 50),
            Product("Слива", "Plum", 46),
            Product("Лимон", "Lemon", 29),
            Product("Лайм", "Lime", 30),
            Product("Грейпфрут", "Grapefruit", 42),
            Product("Малина", "Raspberry", 52),
            Product("Ежевика", "Blackberry", 43),
            Product("Крыжовник", "Gooseberry", 44),
            Product("Инжир", "Fig", 74),
            Product("Финик", "Date", 277),
            Product("Курага", "Dried Apricot", 241),
            Product("Изюм", "Raisin", 299),
            Product("Миндаль", "Almond", 579),
            Product("Грецкий орех", "Walnut", 654),
            Product("Арахис", "Peanut", 567),
            Product("Кешью", "Cashew", 553),
            Product("Фисташки", "Pistachio", 562),
            Product("Семена подсолнечника", "Sunflower Seeds", 584),
            Product("Тыквенные семечки", "Pumpkin Seeds", 446),
            Product("Льняное семя", "Flaxseed", 534),
            Product("Семена чиа", "Chia Seeds", 486),
            Product("Кунжут", "Sesame Seeds", 573),
            Product("Мак", "Poppy Seeds", 525),
            Product("Молоко", "Milk", 42),
            Product("Йогурт", "Yogurt", 59),
            Product("Сыр", "Cheese", 402),
            Product("Творог", "Cottage Cheese", 98),
            Product("Сливки", "Cream", 195),
            Product("Сметана", "Sour Cream", 214),
            Product("Масло сливочное", "Butter", 717),
            Product("Масло подсолнечное", "Sunflower Oil", 884),
            Product("Оливковое масло", "Olive Oil", 884),
            Product("Кукурузное масло", "Corn Oil", 900),
            Product("Рапсовое масло", "Canola Oil", 884),
            Product("Мясо говядины", "Beef", 250),
            Product("Мясо свинины", "Pork", 242),
            Product("Мясо баранины", "Lamb", 294),
            Product("Мясо курицы", "Chicken", 239),
            Product("Мясо индейки", "Turkey", 189),
            Product("Мясо утки", "Duck", 337),
            Product("Мясо кролика", "Rabbit", 173),
            Product("Мясо оленины", "Venison", 158),
            Product("Колбаса", "Sausage", 301),
            Product("Ветчина", "Ham", 145),
            Product("Бекон", "Bacon", 541),
            Product("Сосиски", "Hot Dog", 290),
            Product("Паштеты", "Pâté", 319),
            Product("Рыба лосось", "Salmon", 208),
            Product("Рыба тунец", "Tuna", 132),
            Product("Рыба треска", "Cod", 82),
            Product("Рыба форель", "Trout", 189),
            Product("Рыба палтус", "Halibut", 186),
            Product("Рыба сардины", "Sardines", 208),
            Product("Рыба сельдь", "Herring", 158),
            Product("Рыба скумбрия", "Mackerel", 205),
            Product("Рыба минтай", "Pollock", 92),
            Product("Креветки", "Shrimp", 99),
            Product("Краб", "Crab", 87),
            Product("Лобстер", "Lobster", 89),
            Product("Мидии", "Mussels", 86),
            Product("Устрицы", "Oysters", 81),
            Product("Кальмары", "Squid", 92),
            Product("Грибы шампиньоны", "Champignons", 22),
            Product("Грибы белые", "Porcini", 34),
            Product("Грибы лисички", "Chanterelles", 38),
            Product("Грибы опята", "Honey Agarics", 17),
            Product("Грибы шиитаке", "Shiitake", 34),
            Product("Картофель", "Potato", 77),
            Product("Сладкий картофель", "Sweet Potato", 86),
            Product("Морковь", "Carrot", 41),
            Product("Свекла", "Beetroot", 43),
            Product("Редис", "Radish", 16),
            Product("Репа", "Turnip", 28),
            Product("Капуста белокочанная", "Cabbage", 25),
            Product("Капуста краснокочанная", "Red Cabbage", 31),
            Product("Капуста цветная", "Cauliflower", 25),
            Product("Капуста брокколи", "Broccoli", 34),
            Product("Капуста брюссельская", "Brussels Sprouts", 43),
            Product("Салат", "Lettuce", 15),
            Product("Шпинат", "Spinach", 23),
            Product("Петрушка", "Parsley", 36),
            Product("Укроп", "Dill", 43),
            Product("Базилик", "Basil", 22),
            Product("Мята", "Mint", 44),
            Product("Зеленый лук", "Green Onion", 32),
            Product("Лук репчатый", "Onion", 40),
            Product("Чеснок", "Garlic", 149),
            Product("Томат", "Tomato", 18),
            Product("Огурец", "Cucumber", 16),
            Product("Перец сладкий", "Bell Pepper", 26),
            Product("Перец острый", "Chili Pepper", 40),
            Product("Баклажан", "Eggplant", 25),
            Product("Кабачок", "Zucchini", 17),
            Product("Тыква", "Pumpkin", 26),
            Product("Горошек зеленый", "Green Peas", 81),
            Product("Фасоль зеленая", "Green Beans", 31),
            Product("Фасоль красная", "Red Beans", 333),
            Product("Фасоль белая", "White Beans", 333),
            Product("Соя", "Soybeans", 446),
            Product("Нут", "Chickpeas", 364),
            Product("Лещ", "Bream", 105),
            Product("Осетр", "Sturgeon", 105),
            Product("Треска", "Cod", 82),
            Product("Сом", "Catfish", 119),
            Product("Сельдь", "Herring", 158),
            Product("Щука", "Pike", 84),
            Product("Сазан", "Carp", 127),
            Product("Лосось", "Salmon", 208),
            Product("Кета", "Chum Salmon", 138),
            Product("Горбуша", "Pink Salmon", 152),
            Product("Палтус", "Halibut", 186),
            Product("Минтай", "Pollock", 92),
            Product("Морской окунь", "Sea Bass", 97),
            Product("Мидии", "Mussels", 86),
            Product("Кальмары", "Squid", 92),
            Product("Крабы", "Crabs", 87),
            Product("Креветки", "Shrimps", 99),
            Product("Омары", "Lobsters", 89),
            Product("Мясо лосося", "Salmon meat", 208),
            Product("Форель", "Trout", 189),
            Product("Судак", "Pike-perch", 84),
            Product("Белуга", "Beluga", 234),
            Product("Раки", "Crawfish", 76),
            Product("Моллюски", "Clams", 79),
            Product("Скумбрия", "Mackerel", 205),
            Product("Устрицы", "Oysters", 81),
            Product("Треска", "Codfish", 82),
            Product("Окунь", "Perch", 84),
            Product("Скумбрия", "Mackerel", 205),
            Product("Тунец", "Tuna", 132),
            Product("Палтус", "Halibut", 186),
            Product("Камбала", "Flounder", 70),
            Product("Морской черт", "Monkfish", 76),
            Product("Горбуша", "Pink Salmon", 152),
            Product("Кета", "Chum Salmon", 138),
            Product("Камбала", "Flounder", 70),
            Product("Сельдь", "Herring", 158),
            Product("Минтай", "Pollock", 92),
            Product("Щука", "Pike", 84),
            Product("Сазан", "Carp", 127),
            Product("Мойва", "Capelin", 116),
            Product("Сом", "Catfish", 119),
            Product("Камбала", "Flounder", 70),
            Product("Мидии", "Mussels", 86),
            Product("Устрицы", "Oysters", 81),
            Product("Креветки", "Shrimps", 99),
            Product("Крабы", "Crabs", 87),
            Product("Омары", "Lobsters", 89),
            Product("Кальмары", "Squid", 92),
            Product("Сельдь", "Herring", 158),
            Product("Мойва", "Capelin", 116),
            Product("Моллюски", "Clams", 79),
            Product("Мясо лосося", "Salmon meat", 208),
            Product("Форель", "Trout", 189),
            Product("Треска", "Codfish", 82),
            Product("Лещ", "Bream", 105),
            Product("Осетр", "Sturgeon", 105),
            Product("Сом", "Catfish", 119),
            Product("Сельдь", "Herring", 158),
            Product("Щука", "Pike", 84),
            Product("Сазан", "Carp", 127),
            Product("Мидии", "Mussels", 86),
            Product("Окунь", "Perch", 84),
            Product("Скумбрия", "Mackerel", 205),
            Product("Тунец", "Tuna", 132),
            Product("Палтус", "Halibut", 186),
            Product("Камбала", "Flounder", 70),
            Product("Горбуша", "Pink Salmon", 152),
            Product("Кета", "Chum Salmon", 138),
            Product("Минтай", "Pollock", 92),
            Product("Морской окунь", "Sea Bass", 97),
            Product("Раки", "Crawfish", 76),
            Product("Камбала", "Flounder", 70),
            Product("Скумбрия", "Mackerel", 205),
            Product("Минтай", "Pollock", 92),
            Product("Щука", "Pike", 84),
            Product("Сазан", "Carp", 127),
            Product("Сельдь", "Herring", 158),
            Product("Окунь", "Perch", 84),
            Product("Креветки", "Shrimps", 99),
            Product("Камбала", "Flounder", 70),
            Product("Мойва", "Capelin", 116),
            Product("Сом", "Catfish", 119),
            Product("Окунь", "Perch", 84),
            Product("Сельдь", "Herring", 158),
            Product("Скумбрия", "Mackerel", 205),
            Product("Минтай", "Pollock", 92),
            Product("Сазан", "Carp", 127),
            Product("Раки", "Crawfish", 76),
            Product("Моллюски", "Clams", 79),
            Product("Тунец", "Tuna", 132),
            Product("Палтус", "Halibut", 186),
            Product("Морской черт", "Monkfish", 76),
            Product("Камбала", "Flounder", 70),
            Product("Горбуша", "Pink Salmon", 152),
            Product("Сельдь", "Herring", 158),
            Product("Щука", "Pike", 84),
            Product("Мойва", "Capelin", 116),
            Product("Минтай", "Pollock", 92),
            Product("Мидии", "Mussels", 86),
            Product("Устрицы", "Oysters", 81),
            Product("Креветки", "Shrimps", 99),
            Product("Крабы", "Crabs", 87),
            Product("Омары", "Lobsters", 89),
            Product("Кальмары", "Squid", 92),
            Product("Треска", "Codfish", 82),
            Product("Окунь", "Perch", 84),
            Product("Скумбрия", "Mackerel", 205),
            Product("Тунец", "Tuna", 132),
            Product("Палтус", "Halibut", 186),
            Product("Камбала", "Flounder", 70),
            Product("Минтай", "Pollock", 92),
            Product("Мойва", "Capelin", 116),
            Product("Сазан", "Carp", 127),
            Product("Мидии", "Mussels", 86),
            Product("Щука", "Pike", 84),
            Product("Камбала", "Flounder", 70),
            Product("Сельдь", "Herring", 158),
            Product("Скумбрия", "Mackerel", 205),
            Product("Минтай", "Pollock", 92),
            Product("Сазан", "Carp", 127),
            Product("Раки", "Crawfish", 76),
            Product("Моллюски", "Clams", 79),
            Product("Тунец", "Tuna", 132),
            Product("Палтус", "Halibut", 186),
            Product("Морской черт", "Monkfish", 76),
            Product("Камбала", "Flounder", 70),
            Product("Горбуша", "Pink Salmon", 152),
            Product("Сельдь", "Herring", 158),
            Product("Щука", "Pike", 84),
            Product("Минтай", "Pollock", 92),
            Product("Мидии", "Mussels", 86),
            Product("Устрицы", "Oysters", 81),
            Product("Креветки", "Shrimps", 99),
            Product("Крабы", "Crabs", 87),
            Product("Омары", "Lobsters", 89),
            Product("Кальмары", "Squid", 92),
            Product("Морской окунь", "Sea Bass", 97)
        )


        for (product in products) {
            val values = ContentValues().apply {
                put("name", product.russianName)
                put("name_en", product.englishName)
                put("calories_per_100g", product.caloriesPer100g)
            }
            val rowId = db.insert("Product", null, values)
            Log.d("DatabaseHelper", "Inserted product: ${product.russianName}, Row ID: $rowId")
        }
    }

    data class Product(val russianName: String, val englishName: String, val caloriesPer100g: Int)

    companion object {
        const val DATABASE_NAME = "CalorieMeter.db"
        const val DATABASE_VERSION = 1
    }
}
